# Country list used to get abbreviations
# NOTE: Only used by Amazon right now

COUNTRIES = {
    u'AFGHANISTAN': 'AF',
    u'\xc5LAND ISLANDS': 'AX',
    u'ALBANIA': 'AL',
    u'ALGERIA': 'DZ',
    u'AMERICAN SAMOA': 'AS',
    u'ANDORRA': 'AD',
    u'ANGOLA': 'AO',
    u'ANGUILLA': 'AI',
    u'ANTARCTICA': 'AQ',
    u'ANTIGUA AND BARBUDA': 'AG',
    u'ARGENTINA': 'AR',
    u'ARMENIA': 'AM',
    u'ARUBA': 'AW',
    u'AUSTRALIA': 'AU',
    u'AUSTRIA': 'AT',
    u'AZERBAIJAN': 'AZ',
    u'BAHAMAS': 'BS',
    u'BAHRAIN': 'BH',
    u'BANGLADESH': 'BD',
    u'BARBADOS': 'BB',
    u'BELARUS': 'BY',
    u'BELGIUM': 'BE',
    u'BELIZE': 'BZ',
    u'BENIN': 'BJ',
    u'BERMUDA': 'BM',
    u'BHUTAN': 'BT',
    u'BOLIVIA, PLURINATIONAL STATE OF': 'BO',
    u'BOSNIA AND HERZEGOVINA': 'BA',
    u'BOTSWANA': 'BW',
    u'BOUVET ISLAND': 'BV',
    u'BRAZIL': 'BR',
    u'BRITISH INDIAN OCEAN TERRITORY': 'IO',
    u'BRUNEI DARUSSALAM': 'BN',
    u'BULGARIA': 'BG',
    u'BURKINA FASO': 'BF',
    u'BURUNDI': 'BI',
    u'CAMBODIA': 'KH',
    u'CAMEROON': 'CM',
    u'CANADA': 'CA',
    u'CAPE VERDE': 'CV',
    u'CAYMAN ISLANDS': 'KY',
    u'CENTRAL AFRICAN REPUBLIC': 'CF',
    u'CHAD': 'TD',
    u'CHILE': 'CL',
    u'CHINA': 'CN',
    u'CHRISTMAS ISLAND': 'CX',
    u'COCOS (KEELING) ISLANDS': 'CC',
    u'COLOMBIA': 'CO',
    u'COMOROS': 'KM',
    u'CONGO': 'CG',
    u'CONGO, THE DEMOCRATIC REPUBLIC OF THE': 'CD',
    u'COOK ISLANDS': 'CK',
    u'COSTA RICA': 'CR',
    u"C\xd4TE D'IVOIRE": 'CI',
    u'CROATIA': 'HR',
    u'CUBA': 'CU',
    u'CYPRUS': 'CY',
    u'CZECH REPUBLIC': 'CZ',
    u'DENMARK': 'DK',
    u'DJIBOUTI': 'DJ',
    u'DOMINICA': 'DM',
    u'DOMINICAN REPUBLIC': 'DO',
    u'ECUADOR': 'EC',
    u'EGYPT': 'EG',
    u'EL SALVADOR': 'SV',
    u'EQUATORIAL GUINEA': 'GQ',
    u'ERITREA': 'ER',
    u'ESTONIA': 'EE',
    u'ETHIOPIA': 'ET',
    u'FALKLAND ISLANDS (MALVINAS)': 'FK',
    u'FAROE ISLANDS': 'FO',
    u'FIJI': 'FJ',
    u'FINLAND': 'FI',
    u'FRANCE': 'FR',
    u'FRENCH GUIANA': 'GF',
    u'FRENCH POLYNESIA': 'PF',
    u'FRENCH SOUTHERN TERRITORIES': 'TF',
    u'GABON': 'GA',
    u'GAMBIA': 'GM',
    u'GEORGIA': 'GE',
    u'GERMANY': 'DE',
    u'GHANA': 'GH',
    u'GIBRALTAR': 'GI',
    u'GREECE': 'GR',
    u'GREENLAND': 'GL',
    u'GRENADA': 'GD',
    u'GUADELOUPE': 'GP',
    u'GUAM': 'GU',
    u'GUATEMALA': 'GT',
    u'GUERNSEY': 'GG',
    u'GUINEA': 'GN',
    u'GUINEA-BISSAU': 'GW',
    u'GUYANA': 'GY',
    u'HAITI': 'HT',
    u'HEARD ISLAND AND MCDONALD ISLANDS': 'HM',
    u'HOLY SEE (VATICAN CITY STATE)': 'VA',
    u'HONDURAS': 'HN',
    u'HONG KONG': 'HK',
    u'HUNGARY': 'HU',
    u'ICELAND': 'IS',
    u'INDIA': 'IN',
    u'INDONESIA': 'ID',
    u'IRAN, ISLAMIC REPUBLIC OF': 'IR',
    u'IRAQ': 'IQ',
    u'IRELAND': 'IE',
    u'ISLE OF MAN': 'IM',
    u'ISRAEL': 'IL',
    u'ITALY': 'IT',
    u'JAMAICA': 'JM',
    u'JAPAN': 'JP',
    u'JERSEY': 'JE',
    u'JORDAN': 'JO',
    u'KAZAKHSTAN': 'KZ',
    u'KENYA': 'KE',
    u'KIRIBATI': 'KI',
    u"KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF": 'KP',
    u'KOREA, REPUBLIC OF': 'KR',
    u'KUWAIT': 'KW',
    u'KYRGYZSTAN': 'KG',
    u"LAO PEOPLE'S DEMOCRATIC REPUBLIC": 'LA',
    u'LATVIA': 'LV',
    u'LEBANON': 'LB',
    u'LESOTHO': 'LS',
    u'LIBERIA': 'LR',
    u'LIBYAN ARAB JAMAHIRIYA': 'LY',
    u'LIECHTENSTEIN': 'LI',
    u'LITHUANIA': 'LT',
    u'LUXEMBOURG': 'LU',
    u'MACAO': 'MO',
    u'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF': 'MK',
    u'MADAGASCAR': 'MG',
    u'MALAWI': 'MW',
    u'MALAYSIA': 'MY',
    u'MALDIVES': 'MV',
    u'MALI': 'ML',
    u'MALTA': 'MT',
    u'MARSHALL ISLANDS': 'MH',
    u'MARTINIQUE': 'MQ',
    u'MAURITANIA': 'MR',
    u'MAURITIUS': 'MU',
    u'MAYOTTE': 'YT',
    u'MEXICO': 'MX',
    u'MICRONESIA, FEDERATED STATES OF': 'FM',
    u'MOLDOVA, REPUBLIC OF': 'MD',
    u'MONACO': 'MC',
    u'MONGOLIA': 'MN',
    u'MONTENEGRO': 'ME',
    u'MONTSERRAT': 'MS',
    u'MOROCCO': 'MA',
    u'MOZAMBIQUE': 'MZ',
    u'MYANMAR': 'MM',
    u'NAMIBIA': 'NA',
    u'NAURU': 'NR',
    u'NEPAL': 'NP',
    u'NETHERLANDS': 'NL',
    u'NETHERLANDS ANTILLES': 'AN',
    u'NEW CALEDONIA': 'NC',
    u'NEW ZEALAND': 'NZ',
    u'NICARAGUA': 'NI',
    u'NIGER': 'NE',
    u'NIGERIA': 'NG',
    u'NIUE': 'NU',
    u'NORFOLK ISLAND': 'NF',
    u'NORTHERN MARIANA ISLANDS': 'MP',
    u'NORWAY': 'NO',
    u'OMAN': 'OM',
    u'PAKISTAN': 'PK',
    u'PALAU': 'PW',
    u'PALESTINIAN TERRITORY, OCCUPIED': 'PS',
    u'PANAMA': 'PA',
    u'PAPUA NEW GUINEA': 'PG',
    u'PARAGUAY': 'PY',
    u'PERU': 'PE',
    u'PHILIPPINES': 'PH',
    u'PITCAIRN': 'PN',
    u'POLAND': 'PL',
    u'PORTUGAL': 'PT',
    u'PUERTO RICO': 'PR',
    u'QATAR': 'QA',
    u'R\xc9UNION': 'RE',
    u'ROMANIA': 'RO',
    u'RUSSIAN FEDERATION': 'RU',
    u'RWANDA': 'RW',
    u'SAINT BARTH\xc9LEMY': 'BL',
    u'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA': 'SH',
    u'SAINT KITTS AND NEVIS': 'KN',
    u'SAINT LUCIA': 'LC',
    u'SAINT MARTIN': 'MF',
    u'SAINT PIERRE AND MIQUELON': 'PM',
    u'SAINT VINCENT AND THE GRENADINES': 'VC',
    u'SAMOA': 'WS',
    u'SAN MARINO': 'SM',
    u'SAO TOME AND PRINCIPE': 'ST',
    u'SAUDI ARABIA': 'SA',
    u'SENEGAL': 'SN',
    u'SERBIA': 'RS',
    u'SEYCHELLES': 'SC',
    u'SIERRA LEONE': 'SL',
    u'SINGAPORE': 'SG',
    u'SLOVAKIA': 'SK',
    u'SLOVENIA': 'SI',
    u'SOLOMON ISLANDS': 'SB',
    u'SOMALIA': 'SO',
    u'SOUTH AFRICA': 'ZA',
    u'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS': 'GS',
    u'SPAIN': 'ES',
    u'SRI LANKA': 'LK',
    u'SUDAN': 'SD',
    u'SURINAME': 'SR',
    u'SVALBARD AND JAN MAYEN': 'SJ',
    u'SWAZILAND': 'SZ',
    u'SWEDEN': 'SE',
    u'SWITZERLAND': 'CH',
    u'SYRIAN ARAB REPUBLIC': 'SY',
    u'TAIWAN, PROVINCE OF CHINA': 'TW',
    u'TAJIKISTAN': 'TJ',
    u'TANZANIA, UNITED REPUBLIC OF': 'TZ',
    u'THAILAND': 'TH',
    u'TIMOR-LESTE': 'TL',
    u'TOGO': 'TG',
    u'TOKELAU': 'TK',
    u'TONGA': 'TO',
    u'TRINIDAD AND TOBAGO': 'TT',
    u'TUNISIA': 'TN',
    u'TURKEY': 'TR',
    u'TURKMENISTAN': 'TM',
    u'TURKS AND CAICOS ISLANDS': 'TC',
    u'TUVALU': 'TV',
    u'UGANDA': 'UG',
    u'UKRAINE': 'UA',
    u'UNITED ARAB EMIRATES': 'AE',
    u'UNITED KINGDOM': 'GB',
    u'UNITED STATES': 'US',
    u'UNITED STATES MINOR OUTLYING ISLANDS': 'UM',
    u'URUGUAY': 'UY',
    u'UZBEKISTAN': 'UZ',
    u'VANUATU': 'VU',
    u'VENEZUELA, BOLIVARIAN REPUBLIC OF': 'VE',
    u'VIET NAM': 'VN',
    u'VIRGIN ISLANDS, BRITISH': 'VG',
    u'VIRGIN ISLANDS, U.S.': 'VI',
    u'WALLIS AND FUTUNA': 'WF',
    u'WESTERN SAHARA': 'EH',
    u'YEMEN': 'YE',
    u'ZAMBIA': 'ZM',
    u'ZIMBABWE': 'ZW',
}
